=== ralish/dotfiles/windows/Windows Performance Recorder/wpr.config.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
  Windows Performance Recorder configuration schema
  https://learn.microsoft.com/en-au/windows-hardware/test/wpt/windows-performance-recorder

  Exported from release: Windows 11 25H2

  The XML schema is included in `wpr.exe` as an `RCData` resource.
-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="SimpleValueType">
    <xs:restriction base="xs:unsignedShort">
      <xs:minInclusive value="1"></xs:minInclusive>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="KeyboardShortcutType">
    <xs:attribute name="WinKey" type="xs:boolean" use="required" />
    <xs:attribute name="CtrlKey" type="xs:boolean" use="required" />
    <xs:attribute name="ShiftKey" type="xs:boolean" use="required" />
    <xs:attribute name="AltKey" type="xs:boolean" use="required" />
    <xs:attribute name="CharKey" type="xs:string" use="required" />
    <xs:attribute name="VirtualKeyCode" type="xs:unsignedShort" use="required" />
  </xs:complexType>
  <xs:element name="WindowsPerformanceRecorder">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Configuration">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="MaxProfilesToStart">
                <xs:complexType>
                  <xs:attribute name="Value" type="SimpleValueType" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="QueryRuntimePropertiesInterval">
                <xs:complexType>
                  <xs:attribute name="Value" type="SimpleValueType" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="SaveRecordingKeyboardShortcut" type="KeyboardShortcutType" />
              <xs:element name="SaveWaypointsKeyboardShortcut" type="KeyboardShortcutType" />
              <xs:element name="FireEventKeyboardShortcut" type="KeyboardShortcutType" />
              <xs:element name="NGenPdbsCachePath">
                <xs:complexType>
                  <xs:attribute name="Value" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Version" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ralish/dotfiles/windows/Windows Performance Recorder/wpr.config.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  Windows Performance Recorder configuration
  https://learn.microsoft.com/en-au/windows-hardware/test/wpt/windows-performance-recorder

  Last reviewed release: Windows 11 25H2
  File path: `<InstallDir>\wpr.config.xml`
-->
<WindowsPerformanceRecorder Version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="wpr.config.xsd">
  <Configuration>
    <MaxProfilesToStart Value="64" />
    <QueryRuntimePropertiesInterval Value="1000" />
    <SaveRecordingKeyboardShortcut WinKey="true" CtrlKey="true" ShiftKey="true" AltKey="false" CharKey="r" VirtualKeyCode="0" />
    <SaveWaypointsKeyboardShortcut WinKey="true" CtrlKey="true" ShiftKey="false" AltKey="true" CharKey="w" VirtualKeyCode="0" />
    <FireEventKeyboardShortcut WinKey="true" CtrlKey="true" ShiftKey="false" AltKey="true" CharKey="x" VirtualKeyCode="0" />
    <NGenPdbsCachePath Value="D:\Cache\WPR\NGen PDBs" />
  </Configuration>
</WindowsPerformanceRecorder>
